### ISSUE TITLE
"Load from Twitch" button doesn't work

### ISSUE THREAD

**Issue by 0ember1** [NoobJsPerson/speedrun-timer#17]
When I try to paste a twitch link and use load from twitch button, it redirects me to another page, but it doesn't show the twitch player to see and retime the run at. I remember this issue being for at least several months, and other people are also experiencing it, when is it going to get fixed? 
![image](https://user-images.githubusercontent.com/71174607/214893656-5fba3851-8da2-4fce-a099-8b751fd29466.png)

**Comment by NoobJsPerson** [comment]
Oh It did work for me when i tested it. could you send the link you used so i can use it to fix this issue?

**Comment by 0ember1** [comment]
> Oh It did work for me when i tested it. could you send the link you used so i can use it to fix this issue?

Alright. As I said, I'm not the only one who gets this issue, there are also my friends and colleagues who were using your tool to retime twitch runs, but now it just doesn't work. Anyway, gonna give some info that might help you to fix the issue.

I tried multiple browsers (firefox, chrome, brave), even did it on phone (brave), it doesn't work anywhere.

Links of multiple twitch runs I've used in the retimer:
https://noobjsperson.github.io/speedrun-timer/new_run.html?id=1677182822&type=t
https://noobjsperson.github.io/speedrun-timer/new_run.html?id=1673883683&type=t
https://noobjsperson.github.io/speedrun-timer/new_run.html?id=https://www.twitch.tv/3setz/v/1692020038?sr=a&t=32s&type=t

All of them don't work

**Comment by 0ember1** [comment]
Sorry for reopening, mis-input

**Comment by shenef** [comment]
Interestingly I currently cannot get any twitch video to work, all of them fail with 
```
new_run.js:193 t
v1.js:1 Uncaught MissingElementError: Could not find the provided element: video-div
    at new r (v1.js:1:17463)
    at v1.js:1:24173
    at r [as constructor] (v1.js:1:24273)
    at new r (v1.js:1:25828)
    at new_run.js:245:14
``` 
in the console.

My first guess is that 2ab0bc6 broke it.

**Comment by NoobJsPerson** [comment]
@shenef you were right looks like i commented the div right before my div. my bad! ill fix it shortly

**Comment by NoobJsPerson** [comment]
@0ember1 It should be fixed it now. If the site still looks kinda broken remove site browsing data and it will come back to normal
