### ISSUE TITLE
Copy to clipboard bug,

### ISSUE THREAD

**Issue by badonyt** [NoobJsPerson/speedrun-timer#7]
i cant copy to clipboard, i have found the a fix.

On line 99 of new_run.js replace  document.exec('copy');  with document.execCommand('copy');

I tried on firefox and edge, chrome.

I really like the work you guys / girls did thanks!

Console:

![imagem](https://user-images.githubusercontent.com/78484256/185114947-b7243444-2e11-4676-98fc-08871655fa8e.png)

**Comment by badonyt** [comment]
https://github.com/badonyt/speedrun-timer

**Comment by badonyt** [comment]
and also i cant go back home in my fork, love your work!

**Comment by NoobJsPerson** [comment]
Looks document.exec is obselete. Thank you for telling us :)

**Comment by NoobJsPerson** [comment]
It should be fixed now. If it does for you, close this issue

**Comment by badonyt** [comment]
It works thanks!
